// src/views/AfterSales.vue
<template>
  <div class="after-sales-page">
    <!-- Hero Section -->
    <section class="page-hero">
      <div class="hero-content">
        <h1 data-aos="fade-up">After-Sales Service</h1>
        <p data-aos="fade-up" data-aos-delay="100">
          Comprehensive warranty and support services for all FlashCore SSD products
        </p>
      </div>
    </section>

    <!-- Service Types -->
    <section class="section services">
      <div class="container">
        <h2 class="section-title" data-aos="fade-up">Our Service Commitment</h2>
        <div class="services-grid">
          <div class="service-card" v-for="(service, index) in services" :key="index"
               :data-aos="'fade-up'" :data-aos-delay="index * 100">
            <div class="service-icon">{{ service.icon }}</div>
            <h3>{{ service.title }}</h3>
            <p>{{ service.description }}</p>
            <ul class="service-details">
              <li v-for="(detail, i) in service.details" :key="i">{{ detail }}</li>
            </ul>
          </div>
        </div>
      </div>
    </section>

    <!-- Warranty Policy -->
    <section class="section warranty">
      <div class="container">
        <h2 class="section-title" data-aos="fade-up">Warranty Policy</h2>
        <div class="warranty-content" data-aos="fade-up">
          <div class="warranty-card">
            <div class="warranty-header">
              <span class="warranty-icon">🛡️</span>
              <h3>S100 / M200 Warranty</h3>
            </div>
            <div class="warranty-body">
              <div class="warranty-period">
                <span class="period-number">3</span>
                <span class="period-text">Years</span>
              </div>
              <ul class="warranty-features">
                <li>✓ Hardware defect coverage</li>
                <li>✓ Firmware updates</li>
                <li>✓ Technical support via email</li>
                <li>✓ Free replacement within 7 days</li>
                <li>✓ Data recovery assistance</li>
              </ul>
            </div>
          </div>

          <div class="warranty-card featured">
            <div class="warranty-badge">Recommended</div>
            <div class="warranty-header">
              <span class="warranty-icon">⭐</span>
              <h3>X1 Pro Warranty</h3>
            </div>
            <div class="warranty-body">
              <div class="warranty-period">
                <span class="period-number">5</span>
                <span class="period-text">Years</span>
              </div>
              <ul class="warranty-features">
                <li>✓ All S100/M200 warranty features</li>
                <li>✓ Priority 24/7 phone support</li>
                <li>✓ Advanced replacement service</li>
                <li>✓ Free data recovery (1 time)</li>
                <li>✓ Extended wear-out coverage</li>
                <li>✓ Dedicated technical support</li>
              </ul>
            </div>
          </div>

          <div class="warranty-card">
            <div class="warranty-header">
              <span class="warranty-icon">🏢</span>
              <h3>E500 Enterprise Warranty</h3>
            </div>
            <div class="warranty-body">
              <div class="warranty-period">
                <span class="period-number">5</span>
                <span class="period-text">Years</span>
              </div>
              <ul class="warranty-features">
                <li>✓ All X1 Pro warranty features</li>
                <li>✓ On-site replacement service</li>
                <li>✓ 4-hour response time SLA</li>
                <li>✓ Spare units pre-positioned</li>
                <li>✓ Annual health diagnostics</li>
                <li>✓ Power loss recovery support</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Return & Exchange Policy -->
    <section class="section policy">
      <div class="container">
        <h2 class="section-title" data-aos="fade-up">Return & Exchange Policy</h2>
        <div class="policy-grid">
          <div class="policy-card" data-aos="fade-up" data-aos-delay="100">
            <div class="policy-icon">📦</div>
            <h3>30-Day Return Guarantee</h3>
            <p>If you're not completely satisfied with your purchase, you may return the product within 30 days of delivery for a full refund.</p>
            <ul>
              <li>Product must be in original condition</li>
              <li>Original packaging required</li>
              <li>Proof of purchase needed</li>
              <li>Free return shipping label provided</li>
            </ul>
          </div>

          <div class="policy-card" data-aos="fade-up" data-aos-delay="200">
            <div class="policy-icon">🔄</div>
            <h3>Exchange Policy</h3>
            <p>Exchange your product for a different model or specification within 15 days of purchase.</p>
            <ul>
              <li>One-time exchange per purchase</li>
              <li>Price difference may apply</li>
              <li>Product must be unused</li>
              <li>Quick processing within 48 hours</li>
            </ul>
          </div>

          <div class="policy-card" data-aos="fade-up" data-aos-delay="300">
            <div class="policy-icon">💰</div>
            <h3>Refund Process</h3>
            <p>Refunds are processed within 5-7 business days after we receive and inspect the returned product.</p>
            <ul>
              <li>Refund to original payment method</li>
              <li>Email notification at each step</li>
              <li>Tracking number for return shipment</li>
              <li>Customer service support available</li>
            </ul>
          </div>
        </div>
      </div>
    </section>

    <!-- Support Channels -->
    <section class="section support">
      <div class="container">
        <h2 class="section-title" data-aos="fade-up">Support Channels</h2>
        <div class="support-grid">
          <div class="support-card" data-aos="fade-up" data-aos-delay="100">
            <div class="support-icon">📞</div>
            <h3>Phone Support</h3>
            <p class="support-availability">24/7 Available</p>
            <p class="support-number">+1 (800) 123-4567</p>
            <p>Average wait time: Under 2 minutes</p>
          </div>

          <div class="support-card" data-aos="fade-up" data-aos-delay="200">
            <div class="support-icon">✉️</div>
            <h3>Email Support</h3>
            <p class="support-availability">Response within 4 hours</p>
            <p class="support-number">support@techvision.com</p>
            <p>For non-urgent inquiries</p>
          </div>

          <div class="support-card" data-aos="fade-up" data-aos-delay="300">
            <div class="support-icon">💬</div>
            <h3>Live Chat</h3>
            <p class="support-availability">Mon-Fri, 9AM-6PM EST</p>
            <p class="support-number">Available on website</p>
            <p>Instant support from our team</p>
          </div>

          <div class="support-card" data-aos="fade-up" data-aos-delay="400">
            <div class="support-icon">🎫</div>
            <h3>Ticket System</h3>
            <p class="support-availability">Track your issues</p>
            <p class="support-number">support.techvision.com</p>
            <p>Submit and monitor support tickets</p>
          </div>
        </div>
      </div>
    </section>

    <!-- FAQ Section -->
    <section class="section faq">
      <div class="container">
        <h2 class="section-title" data-aos="fade-up">Frequently Asked Questions</h2>
        <div class="faq-list">
          <div class="faq-item" v-for="(faq, index) in faqs" :key="index"
               :data-aos="'fade-up'" :data-aos-delay="index * 50">
            <div class="faq-question" @click="toggleFaq(index)">
              <h3>{{ faq.question }}</h3>
              <span class="faq-toggle" :class="{ 'active': faq.open }">+</span>
            </div>
            <div class="faq-answer" v-show="faq.open">
              <p>{{ faq.answer }}</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Contact CTA -->
    <section class="section cta">
      <div class="container">
        <div class="cta-content" data-aos="zoom-in">
          <h2>Need Technical Support?</h2>
          <p>Our dedicated support team is ready to assist you with any questions or issues.</p>
          <div class="cta-buttons">
            <button class="btn btn-primary">Contact Support</button>
            <button class="btn btn-secondary">Submit a Ticket</button>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup>
import { ref } from 'vue'

const services = [
  {
    icon: '🔧',
    title: 'Technical Support',
    description: 'Expert assistance for troubleshooting, configuration, and optimization of your products.',
    details: [
      'Remote troubleshooting and diagnostics',
      'Software installation assistance',
      'Configuration optimization',
      'Performance tuning'
    ]
  },
  {
    icon: '📦',
    title: 'Repair Services',
    description: 'Professional repair services for hardware issues with quick turnaround times.',
    details: [
      'Hardware component replacement',
      'Board-level repairs',
      'Firmware restoration',
      'Quality testing after repair'
    ]
  },
  {
    icon: '🎓',
    title: 'Training Services',
    description: 'Comprehensive training programs to help your team maximize product utilization.',
    details: [
      'On-site training sessions',
      'Online certification courses',
      'Custom training programs',
      'User documentation and guides'
    ]
  },
  {
    icon: '📋',
    title: 'Maintenance Contracts',
    description: 'Proactive maintenance agreements to ensure optimal system performance.',
    details: [
      'Scheduled preventive maintenance',
      'System health monitoring',
      'Performance reports',
      'Priority service scheduling'
    ]
  },
  {
    icon: '🔄',
    title: 'Upgrade Services',
    description: 'Keep your systems up-to-date with our professional upgrade services.',
    details: [
      'Hardware upgrade installations',
      'Software migration services',
      'System compatibility assessment',
      'Data migration assistance'
    ]
  },
  {
    icon: '📊',
    title: 'Consulting Services',
    description: 'Expert advice on technology strategy, implementation, and optimization.',
    details: [
      'Technology assessment',
      'Solution architecture design',
      'Implementation planning',
      'ROI analysis and reporting'
    ]
  }
]

const faqs = ref([
  {
    question: 'How do I request a warranty repair?',
    answer: 'You can request a warranty repair by contacting our support team via phone, email, or the ticket system. Please have your product serial number and proof of purchase ready. Our team will guide you through the process and arrange for repair or replacement as needed.',
    open: false
  },
  {
    question: 'What is covered under the standard warranty?',
    answer: 'The standard warranty covers manufacturing defects in materials and workmanship for 12 months from the date of purchase. This includes hardware component failures, software bugs, and firmware issues. It does not cover damage from misuse, accidents, or unauthorized modifications.',
    open: false
  },
  {
    question: 'How long does a typical repair take?',
    answer: 'Standard repairs are completed within 5-7 business days. For Premium and Enterprise warranty holders, we offer expedited service with next-business-day replacement options. You will receive a tracking number to monitor the repair status.',
    open: false
  },
  {
    question: 'Can I extend my warranty coverage?',
    answer: 'Yes, warranty extensions can be purchased at any time during the original warranty period. We offer 1-year and 2-year extension options. Contact our sales team or visit our website to purchase an extension plan.',
    open: false
  },
  {
    question: 'Do you offer on-site support?',
    answer: 'Yes, on-site support is available for Premium and Enterprise warranty customers. Our technicians will visit your location to diagnose and resolve issues. Standard warranty customers can upgrade to include on-site support for an additional fee.',
    open: false
  },
  {
    question: 'What is your return policy?',
    answer: 'We offer a 30-day return guarantee for products purchased directly from TechVision. The product must be in its original condition and packaging. A full refund will be issued within 5-7 business days after we receive and inspect the returned item.',
    open: false
  }
])

const toggleFaq = (index) => {
  faqs.value[index].open = !faqs.value[index].open
}
</script>

<style scoped>
.page-hero {
  padding: 150px 0 100px;
  background: linear-gradient(135deg, #0f172a 0%, #1e1b4b 50%, #0f172a 100%);
  text-align: center;
}

.page-hero h1 {
  font-size: 4rem;
  font-weight: 800;
  color: white;
  margin-bottom: 20px;
}

.page-hero p {
  font-size: 1.3rem;
  color: #94a3b8;
  max-width: 600px;
  margin: 0 auto;
}

.section {
  padding: 80px 0;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 20px;
}

.section-title {
  font-size: 2.5rem;
  font-weight: 700;
  color: white;
  text-align: center;
  margin-bottom: 60px;
}

.services {
  background: #0f172a;
}

.services-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 30px;
}

.service-card {
  background: linear-gradient(135deg, #1e293b 0%, #0f172a 100%);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 20px;
  padding: 35px;
  transition: all 0.3s ease;
}

.service-card:hover {
  transform: translateY(-10px);
  border-color: #667eea;
  box-shadow: 0 20px 40px rgba(102, 126, 234, 0.2);
}

.service-icon {
  font-size: 3rem;
  margin-bottom: 20px;
}

.service-card h3 {
  color: white;
  font-size: 1.3rem;
  margin-bottom: 12px;
}

.service-card p {
  color: #94a3b8;
  line-height: 1.6;
  margin-bottom: 20px;
}

.service-details {
  list-style: none;
  padding: 0;
  margin: 0;
}

.service-details li {
  color: #94a3b8;
  padding: 5px 0;
  padding-left: 20px;
  position: relative;
}

.service-details li::before {
  content: '✓';
  position: absolute;
  left: 0;
  color: #667eea;
}

.warranty {
  background: linear-gradient(135deg, #1e1b4b 0%, #0f172a 100%);
}

.warranty-content {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 30px;
}

.warranty-card {
  background: linear-gradient(135deg, #1e293b 0%, #0f172a 100%);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 20px;
  padding: 30px;
  transition: all 0.3s ease;
  position: relative;
}

.warranty-card.featured {
  border-color: #667eea;
  transform: scale(1.05);
}

.warranty-badge {
  position: absolute;
  top: -12px;
  left: 50%;
  transform: translateX(-50%);
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  padding: 5px 20px;
  border-radius: 50px;
  font-size: 0.8rem;
  font-weight: 600;
}

.warranty-header {
  display: flex;
  align-items: center;
  gap: 15px;
  margin-bottom: 20px;
}

.warranty-icon {
  font-size: 2.5rem;
}

.warranty-header h3 {
  color: white;
  font-size: 1.4rem;
}

.warranty-body {
  text-align: center;
}

.warranty-period {
  margin-bottom: 25px;
}

.period-number {
  font-size: 4rem;
  font-weight: 800;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  display: block;
}

.period-text {
  color: #94a3b8;
  font-size: 1.2rem;
  text-transform: uppercase;
}

.warranty-features {
  list-style: none;
  padding: 0;
  margin: 0;
  text-align: left;
}

.warranty-features li {
  color: #94a3b8;
  padding: 8px 0;
  border-bottom: 1px solid rgba(255, 255, 255, 0.05);
}

.policy {
  background: #0f172a;
}

.policy-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 30px;
}

.policy-card {
  background: linear-gradient(135deg, #1e293b 0%, #0f172a 100%);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 20px;
  padding: 35px;
  transition: all 0.3s ease;
}

.policy-card:hover {
  transform: translateY(-10px);
  border-color: #667eea;
}

.policy-icon {
  font-size: 3rem;
  margin-bottom: 20px;
}

.policy-card h3 {
  color: white;
  font-size: 1.3rem;
  margin-bottom: 15px;
}

.policy-card p {
  color: #94a3b8;
  line-height: 1.6;
  margin-bottom: 20px;
}

.policy-card ul {
  list-style: none;
  padding: 0;
  margin: 0;
}

.policy-card li {
  color: #94a3b8;
  padding: 5px 0;
  padding-left: 20px;
  position: relative;
}

.policy-card li::before {
  content: '•';
  position: absolute;
  left: 0;
  color: #667eea;
}

.support {
  background: linear-gradient(135deg, #1e1b4b 0%, #0f172a 100%);
}

.support-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 30px;
}

.support-card {
  background: linear-gradient(135deg, #1e293b 0%, #0f172a 100%);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 20px;
  padding: 35px;
  text-align: center;
  transition: all 0.3s ease;
}

.support-card:hover {
  transform: translateY(-10px);
  border-color: #667eea;
}

.support-icon {
  font-size: 3rem;
  margin-bottom: 20px;
}

.support-card h3 {
  color: white;
  font-size: 1.3rem;
  margin-bottom: 10px;
}

.support-availability {
  color: #10b981;
  font-weight: 600;
  margin-bottom: 10px;
}

.support-number {
  color: #667eea;
  font-size: 1.1rem;
  font-weight: 600;
  margin-bottom: 10px;
}

.support-card p:last-child {
  color: #94a3b8;
  font-size: 0.9rem;
}

.faq {
  background: #0f172a;
}

.faq-list {
  max-width: 800px;
  margin: 0 auto;
}

.faq-item {
  background: linear-gradient(135deg, #1e293b 0%, #0f172a 100%);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 15px;
  margin-bottom: 15px;
  overflow: hidden;
}

.faq-question {
  padding: 20px 25px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  cursor: pointer;
  transition: all 0.3s ease;
}

.faq-question:hover {
  background: rgba(102, 126, 234, 0.1);
}

.faq-question h3 {
  color: white;
  font-size: 1.1rem;
  margin: 0;
}

.faq-toggle {
  color: #667eea;
  font-size: 1.5rem;
  font-weight: 700;
  transition: transform 0.3s ease;
}

.faq-toggle.active {
  transform: rotate(45deg);
}

.faq-answer {
  padding: 0 25px 20px;
}

.faq-answer p {
  color: #94a3b8;
  line-height: 1.8;
}

.cta {
  background: linear-gradient(135deg, #1e1b4b 0%, #0f172a 100%);
}

.cta-content {
  text-align: center;
  max-width: 600px;
  margin: 0 auto;
}

.cta-content h2 {
  font-size: 2.5rem;
  color: white;
  margin-bottom: 20px;
}

.cta-content p {
  color: #94a3b8;
  font-size: 1.1rem;
  margin-bottom: 35px;
}

.cta-buttons {
  display: flex;
  gap: 20px;
  justify-content: center;
  flex-wrap: wrap;
}

.btn {
  padding: 15px 35px;
  border-radius: 50px;
  font-size: 1rem;
  font-weight: 600;
  text-decoration: none;
  transition: all 0.3s ease;
  display: inline-block;
  cursor: pointer;
}

.btn-primary {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  border: none;
  box-shadow: 0 4px 20px rgba(102, 126, 234, 0.4);
}

.btn-primary:hover {
  transform: translateY(-3px);
  box-shadow: 0 8px 30px rgba(102, 126, 234, 0.6);
}

.btn-secondary {
  background: transparent;
  color: white;
  border: 2px solid rgba(255, 255, 255, 0.3);
}

.btn-secondary:hover {
  background: rgba(255, 255, 255, 0.1);
  border-color: white;
}

@media (max-width: 768px) {
  .page-hero h1 {
    font-size: 2.8rem;
  }

  .section-title {
    font-size: 2rem;
  }

  .services-grid,
  .warranty-content,
  .policy-grid,
  .support-grid {
    grid-template-columns: 1fr;
  }

  .warranty-card.featured {
    transform: scale(1);
  }
}
</style>

// src/components/AfterSales.tsx
import { useState } from 'react'
import ScrollAnimation from './ScrollAnimation'

const services = [
  {
    icon: (
      <svg className="w-8 h-8" fill="none" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" viewBox="0 0 24 24" stroke="currentColor">
        <path d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"></path>
      </svg>
    ),
    title: 'Warranty Service',
    description: 'All TF SSD products come with a 3-year warranty from the date of purchase. During the warranty period, we provide free repair or replacement for hardware failures caused by product quality issues.',
    details: [
      'Warranty Period: 3 Years',
      'Coverage: Non-man-made hardware failures',
      'Service: Free repair or replacement',
      'Response Time: Within 24 hours'
    ],
    gradient: 'from-indigo-500 to-blue-500'
  },
  {
    icon: (
      <svg className="w-8 h-8" fill="none" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" viewBox="0 0 24 24" stroke="currentColor">
        <path d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"></path>
      </svg>
    ),
    title: 'Return & Exchange Policy',
    description: 'Within 7 days of receiving the product, if there are quality issues or the product does not match the description, you can apply for a no-reason return or exchange. We will cover the shipping costs.',
    details: [
      'Return Period: 7 Days',
      'Conditions: Product undamaged, packaging intact',
      'Shipping: Covered by us for quality issues',
      'Refund: Within 3 business days after receiving the return'
    ],
    gradient: 'from-purple-500 to-indigo-500'
  },
  {
    icon: (
      <svg className="w-8 h-8" fill="none" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" viewBox="0 0 24 24" stroke="currentColor">
        <path d="M18.364 5.636l-3.536 3.536m0 5.656l3.536 3.536M9.172 9.172L5.636 5.636m3.536 9.192l-3.536 3.536M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-5 0a4 4 0 11-8 0 4 4 0 018 0z"></path>
      </svg>
    ),
    title: 'Technical Support',
    description: 'We provide professional technical support services to help users solve various technical problems encountered during product use. Support is available via phone, email, and online chat.',
    details: [
      'Service Hours: 24/7',
      'Support Channels: Phone/Email/Online Chat',
      'Response Time: Within 2 hours on business days',
      'Remote Assistance: Available'
    ],
    gradient: 'from-blue-500 to-purple-500'
  },
  {
    icon: (
      <svg className="w-8 h-8" fill="none" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" viewBox="0 0 24 24" stroke="currentColor">
        <path d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.066 2.573c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.573 1.066c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.066-2.573c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"></path>
        <path d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
      </svg>
    ),
    title: 'Repair Service',
    description: 'For products outside the warranty period, we provide professional paid repair services. Repair costs are transparent and reasonable, and the repair process is fully traceable to ensure user rights.',
    details: [
      'Scope: Hardware failure repair',
      'Cost: Quote before repair',
      'Turnaround: 3-5 business days for general failures',
      'Guarantee: 90-day warranty after repair'
    ],
    gradient: 'from-violet-500 to-purple-500'
  },
  {
    icon: (
      <svg className="w-8 h-8" fill="none" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" viewBox="0 0 24 24" stroke="currentColor">
        <path d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"></path>
      </svg>
    ),
    title: 'Customer Consultation',
    description: 'We have a dedicated customer consultation team providing comprehensive consulting services including product selection advice, usage guidance, and troubleshooting.',
    details: [
      'Channels: Phone/Online/Email',
      'Service Hours: Mon-Fri 9:00-18:00',
      'Content: Product selection/Usage guidance',
      'Feedback: Post-consultation satisfaction survey'
    ],
    gradient: 'from-indigo-500 to-violet-500'
  },
  {
    icon: (
      <svg className="w-8 h-8" fill="none" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" viewBox="0 0 24 24" stroke="currentColor">
        <path d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01"></path>
      </svg>
    ),
    title: 'Complaint Handling',
    description: 'We highly value every user\'s feedback and have established a comprehensive complaint handling mechanism to ensure user issues are resolved promptly and effectively.',
    details: [
      'Channels: Hotline/Online/Email',
      'Response Time: Within 24 hours',
      'Follow-up: Dedicated staff throughout',
      'Satisfaction: Follow-up survey after resolution'
    ],
    gradient: 'from-purple-500 to-pink-500'
  }
]

export default function AfterSales() {
  const [expandedIndex, setExpandedIndex] = useState<number | null>(null)

  return (
    <section id="after-sales" className="py-20 bg-[#0a0a0f] relative overflow-hidden">
      {/* Background effects */}
      <div className="absolute inset-0 pointer-events-none">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-indigo-500/5 rounded-full blur-3xl" />
        <div className="absolute top-1/4 right-1/4 w-[400px] h-[400px] bg-purple-500/5 rounded-full blur-3xl" />
        {/* Grid pattern */}
        <div className="absolute inset-0 opacity-5" style={{
          backgroundImage: 'linear-gradient(rgba(99, 102, 241, 0.3) 1px, transparent 1px), linear-gradient(90deg, rgba(99, 102, 241, 0.3) 1px, transparent 1px)',
          backgroundSize: '50px 50px'
        }} />
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Section Header */}
        <ScrollAnimation className="text-center mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-indigo-500/10 backdrop-blur-md border border-indigo-500/20 mb-6">
            <span className="text-indigo-400 text-sm font-medium">After-sales Service</span>
          </div>
          <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold text-white mb-4">
            After-sales Service
          </h2>
          <p className="text-gray-400 text-lg max-w-2xl mx-auto">
            We are committed to providing professional, timely, and thoughtful after-sales service for every customer
          </p>
        </ScrollAnimation>

        {/* Services Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8" style={{ perspective: '1000px' }}>
          {services.map((service, index) => (
            <ScrollAnimation key={index} delay={50 + index * 30}>
              <div
                className="relative group cursor-pointer"
                onClick={() => setExpandedIndex(expandedIndex === index ? null : index)}
                style={{ transformStyle: 'preserve-3d' }}
              >
                {/* Glow effect */}
                <div className={`absolute -inset-2 bg-gradient-to-r ${service.gradient} rounded-xl blur-xl opacity-0 group-hover:opacity-40 transition-all duration-500`} />

                {/* Card with 3D effect */}
                <div className="relative bg-[#111118] rounded-xl p-6 border border-indigo-500/10 group-hover:border-indigo-500/30 transition-all duration-500 h-full transform group-hover:-translate-y-2 group-hover:rotate-x-1">
                  {/* Shimmer effect */}
                  <div className="absolute inset-0 rounded-xl overflow-hidden pointer-events-none">
                    <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent transform -translate-x-full group-hover:translate-x-full transition-transform duration-1000" />
                  </div>

                  {/* Icon */}
                  <div className={`w-16 h-16 bg-gradient-to-br ${service.gradient} rounded-xl flex items-center justify-center mb-6 text-white shadow-lg shadow-indigo-500/20 transform transition-all duration-500 group-hover:scale-110 group-hover:rotate-6 group-hover:shadow-xl group-hover:shadow-indigo-500/30`}>
                    {service.icon}
                  </div>

                  {/* Title */}
                  <h3 className="text-xl font-bold text-white mb-3 flex items-center justify-between">
                    {service.title}
                    <svg
                      className={`w-5 h-5 text-gray-500 transition-transform duration-300 ${expandedIndex === index ? 'rotate-180' : ''}`}
                      fill="none"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path d="M19 9l-7 7-7-7"></path>
                    </svg>
                  </h3>

                  {/* Description */}
                  <p className="text-gray-400 text-sm leading-relaxed mb-4">
                    {service.description}
                  </p>

                  {/* Details - Expandable */}
                  <div className={`overflow-hidden transition-all duration-500 ${expandedIndex === index ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'}`}>
                    <div className="pt-4 border-t border-indigo-500/10">
                      <ul className="space-y-3">
                        {service.details.map((detail, detailIndex) => (
                          <li key={detailIndex} className="flex items-center gap-3 text-sm">
                            <div className={`w-2 h-2 rounded-full bg-gradient-to-r ${service.gradient} flex-shrink-0`} />
                            <span className="text-gray-300">{detail}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>

                  {/* Bottom glow line */}
                  <div className={`absolute bottom-0 left-0 right-0 h-0.5 bg-gradient-to-r ${service.gradient} rounded-b-xl transform scale-x-0 group-hover:scale-x-100 transition-transform duration-500`} />
                </div>
              </div>
            </ScrollAnimation>
          ))}
        </div>

        {/* Contact Information */}
        <ScrollAnimation delay={800}>
          <div className="mt-20 relative">
            {/* Glow effect */}
            <div className="absolute -inset-1 bg-gradient-to-r from-indigo-600 to-purple-600 rounded-2xl blur opacity-20" />

            <div className="relative bg-gradient-to-r from-indigo-900/30 to-purple-900/30 backdrop-blur-xl rounded-2xl p-8 sm:p-10 border border-indigo-500/20">
              <div className="text-center">
                <h3 className="text-2xl sm:text-3xl font-bold text-white mb-4">
                  Contact Us
                </h3>
                <p className="text-gray-300 mb-8 max-w-2xl mx-auto">
                  If you have any questions or need assistance, please don't hesitate to contact our customer service team
                </p>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
                  {[
                    { value: '400-666-6666', label: 'Hotline', icon: '📞' },
                    { value: 'support@tfssd.com', label: 'Email', icon: '✉️' },
                    { value: '24/7', label: 'Service Hours', icon: '🕐' }
                  ].map((contact, index) => (
                    <div key={index} className="group text-center p-6 rounded-xl bg-white/5 hover:bg-white/10 transition-colors duration-300 border border-indigo-500/10 hover:border-indigo-500/30">
                      <div className="text-4xl mb-3">{contact.icon}</div>
                      <div className="text-2xl font-bold text-white mb-2 group-hover:text-transparent group-hover:bg-clip-text group-hover:bg-gradient-to-r group-hover:from-indigo-400 group-hover:to-purple-400 transition-all duration-300">
                        {contact.value}
                      </div>
                      <div className="text-gray-400 text-sm">{contact.label}</div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </ScrollAnimation>
      </div>
    </section>
  )
}
